services:
  - type: web
    name: right-leg-was-you
    runtime: node
    region: singapore
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: NODE_ENV
        value: production
